# Generated by Django 5.1.1 on 2024-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Mobile number already exists'}, max_length=100, null=True, unique=True),
        ),
    ]
