# Generated by Django 5.1.1 on 2024-12-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='offers')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'db_table': 'promos_offers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='offers')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'offers',
                'verbose_name_plural': 'offerses',
                'db_table': 'promos_offerses',
                'ordering': ['-id'],
            },
        ),
    ]
