# Generated by Django 5.1.1 on 2024-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_offer_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='url',
            new_name='url1',
        ),
        migrations.AddField(
            model_name='offers',
            name='image2',
            field=models.ImageField(default=1, upload_to='offers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='image3',
            field=models.ImageField(default=1, upload_to='offers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='url2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='url3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
