# Generated by Django 5.1.1 on 2024-12-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='color',
        ),
        migrations.RemoveField(
            model_name='option',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='option',
            name='storage',
        ),
        migrations.AddField(
            model_name='option',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.color'),
        ),
        migrations.AddField(
            model_name='option',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ram'),
        ),
        migrations.AddField(
            model_name='option',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.storage'),
        ),
    ]
