# Generated by Django 5.1.1 on 2024-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_option_color_remove_option_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
