# Generated by Django 5.1.1 on 2024-12-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_product_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customspecification',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
