# Generated by Django 5.1.1 on 2024-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_customspecification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customspecification',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
