# Generated by Django 5.1.1 on 2025-01-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_product_sales_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',), 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='iconimage',
            options={'ordering': ['id'], 'verbose_name': 'iconimage', 'verbose_name_plural': 'iconimages'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('id',), 'verbose_name': 'option', 'verbose_name_plural': 'options'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'productimage', 'verbose_name_plural': 'productimages'},
        ),
        migrations.AlterModelOptions(
            name='spec',
            options={'ordering': ['id'], 'verbose_name': 'spec', 'verbose_name_plural': 'specs'},
        ),
    ]
