# Generated by Django 5.1.1 on 2025-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='items.option'),
        ),
    ]
