# Generated by Django 5.1.1 on 2024-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cartitem'),
        ('items', '0004_product_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='option',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='items.option'),
        ),
    ]
