# Generated by Django 5.1.1 on 2024-12-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_whishlist'),
        ('items', '0004_product_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='option',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.option'),
        ),
    ]
