# Generated by Django 5.1.1 on 2024-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_coupon_created_by_coupon_created_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.FloatField(default=0),
        ),
    ]
