# Generated by Django 5.1.1 on 2024-12-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_order_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('offer', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'carttotal',
                'verbose_name_plural': 'carttotals',
                'db_table': 'Customer_CartTotal',
                'ordering': ['-id'],
            },
        ),
    ]
