# Generated by Django 5.1.1 on 2024-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_carttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('IN', 'Initiated'), ('PL', 'Placed'), ('IP', 'In progress'), ('DI', 'Dispatched'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='IN', max_length=25),
        ),
    ]
