# Generated by Django 5.1.1 on 2025-01-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(blank=True, choices=[('HM', 'Home'), ('WO', 'Work'), ('OT', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
