# Generated by Django 5.1.1 on 2025-01-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_order_address1_order_address2_order_address_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-id'], 'verbose_name': 'service_request', 'verbose_name_plural': 'service_requests'},
        ),
        migrations.AlterModelTable(
            name='servicerequest',
            table='customers_service_request',
        ),
    ]
